### ISSUE TITLE
Is it ok to add TJS highlight in ks file?

### ISSUE THREAD

**Issue by Odaimoko** [happiness9721/Kirikiri-Adventure-Game-KAG-Script#1]
For example I want to use iscript and endscript, in which are JS-like TJS. I don't know if it's possible to use one language's highlight in another language's file. Is it possible?
And also in exp="" and cond="", there are tjs expression.

**Comment by happiness9721** [comment]
Yes, it is possible now.
But you need to install another extensions.
Install this [extension](https://marketplace.visualstudio.com/items?itemName=happiness9721.tjs) would solve your problem.

**Comment by Odaimoko** [comment]
但是在ks文件里面没有高亮诶，我知道tjs文件里面可以。就是说能不能把tjs的高亮语法整合进ks里面呢？
![image](https://cloud.githubusercontent.com/assets/7827700/26277735/88fc34aa-3dc0-11e7-884f-15e0a7181a31.png)

**Comment by Odaimoko** [comment]
知道了。必须要用[iscript]而不是@iscript。

**Comment by happiness9721** [comment]
對，他現在只認[iscript]
我平常的習慣是官方的tag全部用[]包，自訂的tag用@，
閱讀上比較容易分得出哪個是官方的哪個是自訂的。
差點忘了這門語言最蛋疼的地方是@跟[]是沒差別的。

**Comment by happiness9721** [comment]
@Odaimoko 
請更新到0.0.3後再試試看
現在應該能用@iscript 跟 @endscript了
